version: '3.8'

services:
  bot:
    image: imkrasnyukov/java-wildberries-self-buy
    restart: always
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

#  cache:
#    image: redis:7.0.7-alpine
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - cache:/data

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#volumes:
#  cache:
#    driver: local

volumes:
  pgdata: