package com.lincentpega.javawildberriesselfbuy.service;

public enum SessionState {
    SESSION_STARTED,
    SESSION_CLOSED,
    SITE_ENTERED,
    NUMBER_ENTERED,
    CAPTCHA_ENTERED,
    SMS_CODE_ENTERED,
    CAPTCHA_APPEARED,
    CAPTCHA_CODE_WRONG,
    PUSH_UP_REQUESTED,
    REQUESTED_CODE_AS_SMS,
    SMS_REQUESTED,
    WRONG_CODE_ENTERED,
    AUTHENTICATED,
    ON_GOOD_PAGE,
    ON_UNAVAILABLE_URL,
}
