package com.lincentpega.javawildberriesselfbuy.constants;

public enum SessionState {
    SESSION_STARTED,
    SESSION_CLOSED,
    SITE_ENTERED,
    NUMBER_ENTERED,
    CAPTCHA_ENTERED,
    SMS_CODE_ENTERED,
    CAPTCHA_APPEARED,
    CAPTCHA_CODE_WRONG,
    PUSH_UP_REQUESTED,
    NOTIFICATION_SENT,
    REQUESTED_CODE_AS_SMS,
    SMS_REQUESTED,
    WRONG_CODE_ENTERED,
    AUTHENTICATED,
    GOOD_PAGE_REQUESTED,
    ON_GOOD_PAGE,
    ON_UNAVAILABLE_URL,
    ADDRESS_SENT,
    GOOD_IN_CART,

}
